# Generated by Django 6.0.3 on 2026-03-21 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_mood'),
    ]

    operations = [
        migrations.AddField(
            model_name='assessment',
            name='level',
            field=models.CharField(default='Low', max_length=20),
            preserve_default=False,
        ),
    ]
