# Generated by Django 6.0.3 on 2026-03-22 07:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_assessment_level'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Assessment',
        ),
    ]
