# Generated by Django 6.0.3 on 2026-03-09 15:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mood', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='MoodEntry',
            new_name='Mood',
        ),
    ]
