# Generated by Django 6.0.3 on 2026-03-11 15:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mood', '0003_assessment'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Assessment',
        ),
    ]
