# Generated by Django 6.0.3 on 2026-03-24 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mood', '0005_mood_sentiment_mood_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mood',
            name='note',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='mood',
            name='sentiment',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
